spring:
    datasource:
        url: jdbc:h2:mem:main;NON_KEYWORDS=USER;
        password: password
        username: sa
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: false
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    liquibase:
        change-log: classpath:db/db.changelog-master.xml


# Application Constants
apiPrefix: /api
apiAuthedPrefix: /api/authed

token:
    timeout: 900  # seconds, 15 minutes
    length: 16 # bytes

mailgun:
    api_key: 134dd72ae8a38253b25653ae5d125a3a-77316142-f5c83a7f
    api_url: https://api.mailgun.net/v3/giggyguychess.com/messages
    sending: false # NOTE: ONLY SET FOR TESTING, DON'T WASTE OUR 500 FREE EMAILS
    domain: <mailgun@giggyguychess.com> # hehehehehehehehehe

